### ISSUE TITLE
Missing files and bypassing initial file paths

### ISSUE THREAD

**Issue by p1nh0** [Digitopia/Sonorium#56]
When moving sonorium preset files to another computer they will always stop working,
because we're using absolute paths (ex: "Macintosh HD:/Applications/Sonorium-1.0/sonorium_presets/sonorium_presets.json"). 

The application should bypass disk and user name in order to solve this problem. Then the user should only have move files to a similar path (ex: from ~/Desktop/sonorium_presets/ to ~/Desktop/sonorium_presets/).

Also the user should be warned when files are missing!!!

**Comment by p1nh0** [comment]
Done!

PS: the user is warned when files are missing! Just open the Max window by pressing the 'debug' button

**Comment by jasgomes** [comment]
Que pro ;)

-----------

www.jasg.net

No dia 09/05/2015, às 15:52, p1nh0 <notifications@github.com> escreveu:

**Comment by diogotudela** [comment]
É sempre bom receber boas notícias durante
o esvaziamento digestivo matinal…

PS: Tiago, essa cena do p1nho não soa a “pinho”, 
mas a punho. Até o auto-correct concorda. Com esse
nome e cabelo rapado, começo a suspeitar que curtes
fisting. Over and out.

**Comment by p1nh0** [comment]
fisting+heading

2015-05-10 11:17 GMT+01:00 Diogo Tudela <notifications@github.com>:
